"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

    [[blocks.segments]]
    template = "┌──"
    style = "plain"
    type = "text"

[[blocks]]
alignment = "left"
type = "prompt"

    [[blocks.segments]]
    background = "#3c4251"
    foreground = "#B8C0E0"
    leading_diamond = ""
    style = "diamond"
    template = "{{ .UserName }} "
    type = "session"

    [[blocks.segments]]
    background = "#444c5d"
    foreground = "#B8C0E0"
    powerline_symbol = ""
    style = "powerline"
    template = " {{ .Path }} "
    type = "path"

        [blocks.segments.properties]
        style = "agnoster_short"
        max_depth = 3
        hide_root_location = true
        folder_icon = "…"

    [[blocks.segments]]
    background = "#ffb86c"
    foreground = "#B8C0E0"
    style = "plain"
    template = "  ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}) "
    type = "git"

        [blocks.segments.properties]
        branch_icon = ""
        fetch_stash_count = true
        fetch_status = false
        fetch_upstream_icon = true

    [[blocks.segments]]
    background = "#4C566A"
    foreground = "#4C566A"
    powerline_symbol = ""
    style = "powerline"
    template = "\u200B"
    type = "text"

    [[blocks.segments]]
    background = "#8be9fd"
    foreground = "#B8C0E0"
    style = "plain"
    template = "  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
    type = "node"

    [[blocks.segments]]
    background = "#86BBD8"
    foreground = "#86BBD8"
    powerline_symbol = ""
    style = "powerline"
    template = "\u200B"
    type = "text"

    [[blocks.segments]]
    background = "#06969A"
    foreground = "#06969A"
    powerline_symbol = ""
    style = "powerline"
    template = "\u200B"
    type = "text"

    [[blocks.segments]]
    background = "#33658A"
    foreground = "#B8C0E0"
    style = "diamond"
    template = " {{ .CurrentDate | date .Format }} "
    trailing_diamond = ""
    type = "time"

    [blocks.segments.properties]
    time_format = "03:04pm"

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

    [[blocks.segments]]
    foreground = "#B8C0E0"
    style = "plain"
    template = "└─</>{{ if .Root }}<lightRed>#</>{{ else }}${{ end }}"
    type = "text"


[[blocks]]
alignment = "left"
type = "rprompt"

    [[blocks.segments]]
    background = "#f1fa8c"
    foreground = "#B8C0E0"
    invert_powerline = true
    leading_diamond = ""
    style = "diamond"
    template = "  {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"
    trailing_diamond = ""
    type = "aws"

