"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on   = [ "g", "l" ]
run  = "plugin lazygit"
desc = "Run Lazygit"

[[manager.prepend_keymap]]
on = [ "'", ";" ]
run = "plugin custom-shell --args=pwsh"
desc = "custom-shell as default"

[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"